=== luciasanchezm/COVID-MineriaDatos/covid.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT covid (Persona+)>
<!ELEMENT Persona EMPTY>
<!ATTLIST Persona Edad CDATA #REQUIRED>
<!ATTLIST Persona Nivel (NiÃ±o | Joven | Adulto | Anciano) #REQUIRED>
<!ATTLIST Persona Dia (LunesViernes | SabadoDomingo) #REQUIRED>
<!ATTLIST Persona Turno (Matutino | Vespertino | Nocturno) #REQUIRED>
<!ATTLIST Persona Hora CDATA #REQUIRED>
<!ATTLIST Persona Evento (Social | Familiar | Negocio | Deportivo) #REQUIRED>
<!ATTLIST Persona TipoLugarEvento (Cerrado | AireLibre | SemiAbierto) #REQUIRED>
<!ATTLIST Persona NoPersonas CDATA #REQUIRED>
<!ATTLIST Persona SanaDistancia (Si | No) #REQUIRED>
<!ATTLIST Persona UsoCubrebocas (Si | No) #REQUIRED>
<!ATTLIST Persona Genero (Masculino | Femenino) #REQUIRED>
<!ATTLIST Persona SeContagio (Si | No) #REQUIRED>

=== luciasanchezm/COVID-MineriaDatos/covid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE covid SYSTEM "./covid.dtd">

<covid>
	<Persona Edad="54.0" Nivel="Adulto" Dia="LunesViernes" Turno="Matutino" Hora="3.0" Evento="Negocio" TipoLugarEvento="SemiAbierto" NoPersonas="54.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Femenino" SeContagio="No" />
	<Persona Edad="16.0" Nivel="Joven" Dia="LunesViernes" Turno="Matutino" Hora="23.0" Evento="Familiar" TipoLugarEvento="Cerrado" NoPersonas="21.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="36.0" Nivel="Adulto" Dia="LunesViernes" Turno="Matutino" Hora="18.0" Evento="Negocio" TipoLugarEvento="SemiAbierto" NoPersonas="93.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Femenino" SeContagio="No" />
	<Persona Edad="1.0" Nivel="Niño" Dia="LunesViernes" Turno="Nocturno" Hora="24.0" Evento="Negocio" TipoLugarEvento="Cerrado" NoPersonas="77.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="97.0" Nivel="Anciano" Dia="LunesViernes" Turno="Nocturno" Hora="1.0" Evento="Negocio" TipoLugarEvento="Cerrado" NoPersonas="14.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Femenino" SeContagio="Si" />
	<Persona Edad="33.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="6.0" Evento="Deportivo" TipoLugarEvento="SemiAbierto" NoPersonas="94.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="4.0" Nivel="Niño" Dia="LunesViernes" Turno="Matutino" Hora="4.0" Evento="Social" TipoLugarEvento="Cerrado" NoPersonas="69.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Femenino" SeContagio="No" />
	<Persona Edad="37.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="17.0" Evento="Social" TipoLugarEvento="AireLibre" NoPersonas="32.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="36.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="24.0" Evento="Deportivo" TipoLugarEvento="SemiAbierto" NoPersonas="60.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Femenino" SeContagio="No" />
	<Persona Edad="15.0" Nivel="Joven" Dia="LunesViernes" Turno="Matutino" Hora="23.0" Evento="Negocio" TipoLugarEvento="SemiAbierto" NoPersonas="59.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="11.0" Nivel="Niño" Dia="LunesViernes" Turno="Nocturno" Hora="17.0" Evento="Familiar" TipoLugarEvento="Cerrado" NoPersonas="87.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Masculino" SeContagio="No" />
	<Persona Edad="18.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="1.0" Evento="Negocio" TipoLugarEvento="Cerrado" NoPersonas="21.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Femenino" SeContagio="Si" />
	<Persona Edad="79.0" Nivel="Anciano" Dia="LunesViernes" Turno="Matutino" Hora="9.0" Evento="Deportivo" TipoLugarEvento="Cerrado" NoPersonas="55.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Masculino" SeContagio="No" />
	<Persona Edad="60.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="6.0" Evento="Negocio" TipoLugarEvento="AireLibre" NoPersonas="38.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Masculino" SeContagio="Si" />
	<Persona Edad="3.0" Nivel="Niño" Dia="LunesViernes" Turno="Nocturno" Hora="20.0" Evento="Familiar" TipoLugarEvento="AireLibre" NoPersonas="90.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Femenino" SeContagio="Si" />
	<Persona Edad="14.0" Nivel="Joven" Dia="LunesViernes" Turno="Nocturno" Hora="18.0" Evento="Deportivo" TipoLugarEvento="SemiAbierto" NoPersonas="19.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="95.0" Nivel="Anciano" Dia="LunesViernes" Turno="Matutino" Hora="18.0" Evento="Social" TipoLugarEvento="AireLibre" NoPersonas="34.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="10.0" Nivel="Niño" Dia="LunesViernes" Turno="Nocturno" Hora="22.0" Evento="Deportivo" TipoLugarEvento="Cerrado" NoPersonas="91.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="99.0" Nivel="Anciano" Dia="LunesViernes" Turno="Vespertino" Hora="3.0" Evento="Social" TipoLugarEvento="SemiAbierto" NoPersonas="18.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="18.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="7.0" Evento="Familiar" TipoLugarEvento="AireLibre" NoPersonas="79.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Masculino" SeContagio="Si" />
	<Persona Edad="97.0" Nivel="Anciano" Dia="LunesViernes" Turno="Vespertino" Hora="17.0" Evento="Negocio" TipoLugarEvento="SemiAbierto" NoPersonas="61.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Masculino" SeContagio="No" />
	<Persona Edad="42.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="16.0" Evento="Deportivo" TipoLugarEvento="Cerrado" NoPersonas="46.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="Si" />
	<Persona Edad="95.0" Nivel="Anciano" Dia="LunesViernes" Turno="Matutino" Hora="1.0" Evento="Familiar" TipoLugarEvento="Cerrado" NoPersonas="6.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Masculino" SeContagio="No" />
	<Persona Edad="86.0" Nivel="Anciano" Dia="LunesViernes" Turno="Matutino" Hora="13.0" Evento="Social" TipoLugarEvento="Cerrado" NoPersonas="55.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="Si" />
	<Persona Edad="58.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="8.0" Evento="Negocio" TipoLugarEvento="SemiAbierto" NoPersonas="17.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Femenino" SeContagio="No" />
	<Persona Edad="46.0" Nivel="Adulto" Dia="LunesViernes" Turno="Matutino" Hora="18.0" Evento="Familiar" TipoLugarEvento="Cerrado" NoPersonas="43.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="55.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="20.0" Evento="Social" TipoLugarEvento="AireLibre" NoPersonas="2.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Femenino" SeContagio="Si" />
	<Persona Edad="91.0" Nivel="Anciano" Dia="LunesViernes" Turno="Nocturno" Hora="16.0" Evento="Social" TipoLugarEvento="AireLibre" NoPersonas="97.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="20.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="1.0" Evento="Negocio" TipoLugarEvento="AireLibre" NoPersonas="82.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="23.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="13.0" Evento="Familiar" TipoLugarEvento="SemiAbierto" NoPersonas="66.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="53.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="4.0" Evento="Familiar" TipoLugarEvento="AireLibre" NoPersonas="41.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="Si" />
	<Persona Edad="9.0" Nivel="Niño" Dia="LunesViernes" Turno="Vespertino" Hora="3.0" Evento="Negocio" TipoLugarEvento="AireLibre" NoPersonas="75.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Femenino" SeContagio="Si" />
	<Persona Edad="50.0" Nivel="Adulto" Dia="LunesViernes" Turno="Matutino" Hora="7.0" Evento="Social" TipoLugarEvento="Cerrado" NoPersonas="30.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="5.0" Nivel="Niño" Dia="LunesViernes" Turno="Matutino" Hora="7.0" Evento="Familiar" TipoLugarEvento="AireLibre" NoPersonas="5.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="29.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="12.0" Evento="Deportivo" TipoLugarEvento="Cerrado" NoPersonas="92.0" SanaDistancia="No" UsoCubrebocas="No" Genero="Masculino" SeContagio="Si" />
	<Persona Edad="88.0" Nivel="Anciano" Dia="LunesViernes" Turno="Nocturno" Hora="22.0" Evento="Social" TipoLugarEvento="AireLibre" NoPersonas="61.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Masculino" SeContagio="No" />
	<Persona Edad="89.0" Nivel="Anciano" Dia="LunesViernes" Turno="Matutino" Hora="24.0" Evento="Familiar" TipoLugarEvento="AireLibre" NoPersonas="56.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="Si" />
	<Persona Edad="33.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="23.0" Evento="Deportivo" TipoLugarEvento="SemiAbierto" NoPersonas="61.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Masculino" SeContagio="No" />
	<Persona Edad="99.0" Nivel="Anciano" Dia="LunesViernes" Turno="Vespertino" Hora="1.0" Evento="Deportivo" TipoLugarEvento="AireLibre" NoPersonas="47.0" SanaDistancia="Si" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="59.0" Nivel="Adulto" Dia="LunesViernes" Turno="Matutino" Hora="11.0" Evento="Familiar" TipoLugarEvento="AireLibre" NoPersonas="53.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="87.0" Nivel="Anciano" Dia="LunesViernes" Turno="Vespertino" Hora="10.0" Evento="Negocio" TipoLugarEvento="Cerrado" NoPersonas="43.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Femenino" SeContagio="No" />
	<Persona Edad="21.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="15.0" Evento="Negocio" TipoLugarEvento="Cerrado" NoPersonas="80.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
	<Persona Edad="64.0" Nivel="Adulto" Dia="LunesViernes" Turno="Vespertino" Hora="13.0" Evento="Social" TipoLugarEvento="SemiAbierto" NoPersonas="20.0" SanaDistancia="Si" UsoCubrebocas="No" Genero="Femenino" SeContagio="No" />
	<Persona Edad="68.0" Nivel="Adulto" Dia="LunesViernes" Turno="Nocturno" Hora="3.0" Evento="Social" TipoLugarEvento="SemiAbierto" NoPersonas="51.0" SanaDistancia="No" UsoCubrebocas="Si" Genero="Masculino" SeContagio="No" />
